title: "[Idea] "
body:
  - type: markdown
    attributes:
      value: |
        ## Idea / 想法
        Share your brilliant ideas with the community!
        与社区分享您的绝妙想法！

  - type: textarea
    id: description
    attributes:
      label: Idea Description / 想法描述
      description: What do you want to add or improve? / 您希望增加或改进什么？
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case / 使用场景
      description: How would this solve a problem? / 这将如何解决问题？
    validations:
      required: true

  - type: dropdown
    id: specific-platform
    attributes:
      label: Platform / 平台
      options:
        - All Platforms (所有平台)
        - Browser Extension (浏览器扩展)
        - Userscript (油猴脚本)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions / 替代方案
      description: Have you considered other ways? / 您是否考虑过其他方法？
    validations:
      required: false
