title: "[Showcase] "
body:
  - type: markdown
    attributes:
      value: |
        ## Showcase / 作品展示
        Show off what you've built with Ophel!
        展示您使用 Ophel 制作的成果！

  - type: textarea
    id: description
    attributes:
      label: Description / 描述
      description: What did you build or how are you using Ophel? / 您做了什么，或者您是如何使用 Ophel 的？
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link / 链接
      description: URL to your repo, script, or demo. / 您的仓库、脚本或演示链接。
      placeholder: https://...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / 截图
      description: Drag and drop images here to show off your work. / 请将图片拖拽至此以展示您的成果。
    validations:
      required: false
